-- Drop foreign key constraints so any guide/article ID can be liked and bookmarked
alter table public.guide_likes drop constraint if exists guide_likes_guide_id_fkey;
alter table public.bookmarks drop constraint if exists bookmarks_guide_id_fkey;

-- Ensure all current articles exist in public.guides for joins
insert into public.guides (id, title, summary, content, author_name, category, prodi_tags, semester, initials, accent, views_count)
values
  ('setup-wsl2-ubuntu-webdev', 'Setup Lengkap WSL2 Ubuntu 24.04 untuk Web Development', 'Panduan instalasi dan konfigurasi native Linux kernel di Windows menggunakan WSL2 untuk kebutuhan praktikum web, lengkap dengan NVM, PHP, dan VS Code integration.', 'Markdown content in articles/setup-wsl2-ubuntu-webdev.md', 'Mu''adz Hudzaifah', 'Web & Tooling', array['TRM', 'IF', 'SI'], 2, 'WSL', '#00ff66', 156),
  ('format-margin-laporan-4433', 'Standar Baku Format Margin Laporan Praktikum & TA (4-4-3-3)', 'Panduan tata letak layout dokumen akademik Universitas Boash. Aturan margin 4-4-3-3, pemisahan nomor romawi dengan angka arab via section break, dan struktur baku bab.', 'Markdown content in articles/format-margin-laporan-4433.md', 'Divisi Kemahasiswaan HIMATRA', 'Akademik & Laporan', array['SEMUA'], 1, '4433', '#22c55e', 248),
  ('jaringan-routing-vlan-cisco', 'Konfigurasi Inter-VLAN Routing & Trunking pada Cisco Packet Tracer', 'Tutorial konfigurasi jaringan switch layer-2 dan router on-a-stick untuk memisahkan segmentasi traffic mahasiswa dan dosen di lab praktikum.', 'Markdown content in articles/jaringan-routing-vlan-cisco.md', 'Mu''adz Hudzaifah', 'Jaringan Komputer', array['TRM', 'IF', 'SRK'], 3, 'VLAN', '#34d399', 114),
  ('basis-data-relasional-normalisasi', 'Panduan Praktis Normalisasi Basis Data (1NF, 2NF, 3NF)', 'Memahami teknik dekomposisi tabel anomali menjadi bentuk normal 1NF, 2NF, dan 3NF pada studi kasus sistem akademik kampus.', 'Markdown content in articles/basis-data-relasional-normalisasi.md', 'Divisi Kemahasiswaan HIMATRA', 'Basis Data', array['TRM', 'IF', 'SI'], 2, 'SQL', '#10b981', 130),
  ('algoritma-struktur-data-dasar', 'Implementasi Struktur Data Stack & Queue pada Praktikum Pemrograman', 'Memahami logika LIFO (Last In First Out) dan FIFO (First In First Out) dengan implementasi Python murni serta analisis kompleksitas waktu O(1).', 'Markdown content in articles/algoritma-struktur-data-dasar.md', 'Mu''adz Hudzaifah', 'Algoritma & Pemrograman', array['TRM', 'IF', 'SRK'], 1, 'PY', '#00ff66', 98),
  ('wokwi-esp32-mqtt-hivemq', 'Simulasi Telemetri ESP32 & MQTT HiveMQ di Browser (Tanpa Alat Fisik)', 'Panduan lengkap merangkai sensor DHT22 dan ESP32 di simulator Wokwi, publish data suhu/kelembaban via protokol MQTT ke broker HiveMQ Cloud, dan subscribe payload JSON.', 'Markdown content in articles/wokwi-esp32-mqtt-hivemq.md', 'Mu''adz Hudzaifah', 'IoT & Embedded', array['TRM', 'Mekatronika', 'SRK'], 3, 'IOT', '#059669', 85),
  ('git-workflow-conflict-detached-head', 'Menyelamatkan Kerja Tim: Mengatasi Merge Conflict & Detached HEAD', 'Solusi langkah demi langkah ketika git rebase gagal, branch stuck di status detached HEAD, dan panduan resolusi merge conflict secara aman tanpa kehilangan kode teman.', 'Markdown content in articles/git-workflow-conflict-detached-head.md', 'Mu''adz Hudzaifah', 'Git & DevOps', array['TRM', 'IF', 'SI', 'SRK'], 2, 'GIT', '#10b981', 92),
  ('blender-to-unity-pipeline', 'Pipeline Export Model 3D Blender ke Unity Engine Tanpa Masalah Rotasi', 'Standarisasi export format FBX dari Blender ke Unity, mengatasi sumbu koordinat terbalik (-Z vs +Y), scale transform 100x bug, dan embed texture material secara presisi.', 'Markdown content in articles/blender-to-unity-pipeline.md', 'Ardi Haryanto', 'Game & Multimedia', array['TRM'], 4, '3D', '#34d399', 78),
  ('metodologi-mdlc-multimedia', 'Penerapan Metodologi MDLC (Luther-Sutopo) pada Proyek Multimedia', 'Membedah 6 fase Multimedia Development Life Cycle (Concept, Design, Material Collecting, Assembly, Testing, Distribution) yang wajib ada di Bab 3 proposal TA mahasiswa TRM.', 'Markdown content in articles/metodologi-mdlc-multimedia.md', 'Muhammad Bariq', 'Metodologi Penelitian', array['TRM'], 6, 'MDLC', '#22c55e', 64),
  ('panduan-kontribusi', 'Panduan & Ketentuan Kontribusi Artikel Jurnal KATAKATING', 'Syarat, ketentuan akademik, format metadata frontmatter, dan tata cara mengirimkan tulisan jurnal/artikel praktikum ke KATAKATING via formulir web atau GitHub Pull Request.', 'Markdown content in articles/panduan-kontribusi.md', 'Divisi Kemahasiswaan HIMATRA', 'Kontribusi & Panduan', array['SEMUA'], 1, 'DOC', '#00ff66', 190)
on conflict (id) do update set
  title = excluded.title,
  summary = excluded.summary,
  category = excluded.category,
  author_name = excluded.author_name;
